name: Test component
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the harsh-ui reposistory
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test-storybook
