name: Test component
on: push
jobs:
  test:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    steps:
      - name: Get the harsh-ui reposistory
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: npm run build-storybook --quite
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,Test" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --slient" \
          "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"
